### ISSUE TITLE
Update CodeStyle Wiki

### ISSUE THREAD

**Issue by ztkmkoo** [ztkmkoo/dss#122]
### motivation
In resolving #36, i recognized that the code style wiki need improvement. 

### to do
We talk a lots in pr #108. And we decide:

The class code convention like
``` java
class Foo {

    // static fields
    // static initializer
    // static methods
    // instance fields
    // constructors
    // instance methods
    // static inner class
    // inner class
}
```

But there are some exceptions that, 
- take serialVersionUID static field at the top the of Serializable class
- take logger field at the top the of class

**Comment by ztkmkoo** [comment]
@Alencion @Amazansia 
Any missing part?

**Comment by ztkmkoo** [comment]
Please update https://github.com/ztkmkoo/dss/wiki/Code-Style(KR) this wiki

**Comment by Alencion** [comment]
Hi, @ztkmkoo @Amazansia 

I have some question.

1. Will we allow both non-static and static loggers? 
2. Logger field always should be on top unless static keyword? 

Ref : http://slf4j.org/faq.html#declared_static

**Comment by ztkmkoo** [comment]
Hi @Alencion 

I read your slfj document.
1. I think we still need static logger in some cases. There are many advantages with using static logger and i do not want to pass the logger as a parameter to a static method.
``` java
private static void someMethod(Logger logger, String name) {
  logger.info("Hello {}", name);
}
```
(Of cource, we can design the class that we do not have to use logger in static method, then we do not need static logger.)

2. I suggest that
  - logger field usually on top of the class
  - in serializable class logger will be position after serialVersionUID
  - in serializable class not recommend using logger
  - logger should be final

@Alencion @Amazansia @RulLu16 @Doyuni 
Please give some advices.

**Comment by Alencion** [comment]
I agree to your suggestion.

I think the logger should not need static.

**Comment by Alencion** [comment]
I updated the code style wiki (KR). 

If you have any idea, plz tell me.

**Comment by ztkmkoo** [comment]
> 
> 
> I updated the code style wiki (KR).
> 
> If you have any idea, plz tell me.

Thank you for the job.
I approval your update.

**Comment by ztkmkoo** [comment]
I will close this job. If any opinion, please reopen this issue or create new issue.
