### ISSUE TITLE
Inspect code style

### ISSUE THREAD

**Issue by ztkmkoo** [ztkmkoo/dss#36]
Some codes do not follow the code style guide rule.
Find the mistake and patch it.

Here is the code style rule in korean.
https://github.com/ztkmkoo/dss/wiki/Code-Style(KR)

**Comment by Amazansia** [comment]
Assign it to me.

**Comment by ztkmkoo** [comment]
@Amazansia 
Hi, it looks i miss description bout class format.

``` java
class Foo {

    // static fields
    // static initializer
    // static methods
    // instance fields
    // constructors
    // instance methods
}
```
