### ISSUE TITLE
Add rest server tests

### ISSUE THREAD

**Issue by ztkmkoo** [ztkmkoo/dss#44]
Please add rest server tests to dss-server module.
Check if all the functions works, if not please report the bugs.

You may need to add some http client dependency and complete the test.

Recommended tests:
- basic rest test. (normal json request and its expected response)
- check if contents types and encode module works well

**Comment by ztkmkoo** [comment]
@Alencion

**Comment by Alencion** [comment]
Can i try to solve this one?
