### ISSUE TITLE
[BUG] Project-Tuturial(KR) is not working

### ISSUE THREAD

**Issue by MunSeongUk** [ztkmkoo/dss#66]
I have tried following the Project Tutorial(KR)  in wiki but it didn't work.

I set up the project like this
    <artifactId>dss-server</artifactId>
    <version>0.3.0.0</version> 
<- which is previous version
    <artifactId>dss-server</artifactId>
    <version>0.3.1.0</version>
<- which is current version
    <artifactId>dss-server</artifactId>
    <version>0.0.3</version>
<- which is guided version in Project Tutorial(KR)
but all of them is not work.

this is error log

"C:\Program Files\Java\jdk-11.0.7\bin\java.exe" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA 2020.1.3\lib\idea_rt.jar=55031:C:\Program Files\JetBrains\IntelliJ IDEA 2020.1.3\bin" -Dfile.encoding=UTF-8 -classpath C:\Users\door6\Desktop\contributon\dss\dss-server\target\classes;C:\Users\door6\Desktop\contributon\dss\dss-core\target\classes;C:\Users\door6\.m2\repository\io\netty\netty-all\4.1.45.Final\netty-all-4.1.45.Final.jar;C:\Users\door6\.m2\repository\com\fasterxml\jackson\core\jackson-core\2.10.2\jackson-core-2.10.2.jar;C:\Users\door6\.m2\repository\com\fasterxml\jackson\core\jackson-databind\2.10.2\jackson-databind-2.10.2.jar;C:\Users\door6\.m2\repository\com\fasterxml\jackson\core\jackson-annotations\2.10.2\jackson-annotations-2.10.2.jar;C:\Users\door6\.m2\repository\ch\qos\logback\logback-classic\1.2.3\logback-classic-1.2.3.jar;C:\Users\door6\.m2\repository\ch\qos\logback\logback-core\1.2.3\logback-core-1.2.3.jar;C:\Users\door6\.m2\repository\com\typesafe\akka\akka-actor-typed_2.13\2.6.3\akka-actor-typed_2.13-2.6.3.jar;C:\Users\door6\.m2\repository\org\scala-lang\scala-library\2.13.1\scala-library-2.13.1.jar;C:\Users\door6\.m2\repository\com\typesafe\akka\akka-actor_2.13\2.6.3\akka-actor_2.13-2.6.3.jar;C:\Users\door6\.m2\repository\com\typesafe\config\1.4.0\config-1.4.0.jar;C:\Users\door6\.m2\repository\org\scala-lang\modules\scala-java8-compat_2.13\0.9.0\scala-java8-compat_2.13-0.9.0.jar;C:\Users\door6\.m2\repository\com\typesafe\akka\akka-slf4j_2.13\2.6.3\akka-slf4j_2.13-2.6.3.jar;C:\Users\door6\.m2\repository\org\slf4j\slf4j-api\1.7.30\slf4j-api-1.7.30.jar io.github.ztkmkoo.dss.server.rest.DssRestServer
22:50:38,851 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
22:50:38,852 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
22:50:38,854 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/C:/Users/door6/Desktop/contributon/dss/dss-server/target/classes/logback.xml]
22:50:39,057 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
22:50:39,059 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
22:50:39,073 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
22:50:39,189 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - This appender no longer admits a layout as a sub-component, set an encoder instead.
22:50:39,189 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
22:50:39,189 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
22:50:39,191 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
22:50:39,191 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
22:50:39,192 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
22:50:39,195 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@1fe20588 - Registering current configuration as safe fallback point

2020-07-21 22:50:40 [INFO ] [Slf4jLogger.scala]applyOrElse(104) : Slf4jLogger started
2020-07-21 22:50:40 [INFO ] [DssRestServer.java]start(69) : Create actor system: akka://system
2020-07-21 22:50:40 [INFO ] [DssRestChannelInitializer.java]dssRestChannelInitializer(121) : Setup dssRestChannelInitializer
2020-07-21 22:50:40 [INFO ] [DssRestChannelInitializer.java]newAllocatedDssRestHandler(57) : freeHandlerQueue is empty. try to initialize new one: rest-handler-1
2020-07-21 22:50:40 [WARN ] [DssRestMasterActor.java]dssRestPathResolver(35) : Service list is empty
2020-07-21 22:50:40 [INFO ] [DssRestChannelInitializer.java]newAllocatedDssRestHandler(57) : freeHandlerQueue is empty. try to initialize new one: rest-handler-2
2020-07-21 22:50:40 [INFO ] [DssRestHandler.java]dssRestHandler(201) : Setup dssRestHandler: rest-handler-1
2020-07-21 22:50:40 [INFO ] [DssRestHandler.java]dssRestHandler(201) : Setup dssRestHandler: rest-handler-2

**Comment by ztkmkoo** [comment]
@MunSeongUk Hi,

i tried with 0.3.0.0 and worked.

``` xml
        <dependency>
            <groupId>io.github.ztkmkoo</groupId>
            <artifactId>dss-server</artifactId>
            <version>0.3.0.0</version>
        </dependency>
```

``` java
public class Test {

    public static void main(String[] args) throws ExecutionException, InterruptedException {

        DssRestServer dssRestServer = new DssRestServer("127.0.0.1", 8181);
        dssRestServer.start();
    }
}
```

telnet 127.0.0.1 8181 work.

**Comment by ztkmkoo** [comment]
@MunSeongUk 
HI,
#79 publish 0.4.3 and fix the tutorial bug. please check.
