### ISSUE TITLE
Fix maven dependencies

### ISSUE THREAD

**Issue by ztkmkoo** [ztkmkoo/dss#68]
![image](https://user-images.githubusercontent.com/26991409/88122624-10ae1100-cc04-11ea-96b0-81ba1e00fd0c.png)

https://github.com/ztkmkoo/dss/network/dependencies

if we set the dependency version in prpoerty, the github dependency not read it.
I dont know if it is a bug.

1, add the version directly to the dependency. => it is hard to manage the library versions
2. report bug or fix the bug (reporting here maybe https://github.community/ )
3. googling the solution
4. some way

**Comment by chusnaval** [comment]
Hi,
I think this is not possible as you can see in:
https://stackoverflow.com/questions/40114869/maven-pom-file-externalizing-dependency-versions-to-a-properties-file

or

https://stackoverflow.com/questions/14725197/reading-properties-file-from-pom-file-in-maven

Regards.

**Comment by ztkmkoo** [comment]
@chusnaval 
Thank you guy.. 

How bout setting the version in each pom.xml?

**Comment by chusnaval** [comment]
Oh! i'm sorry, I misunderstood the problem, i'm gonna googling to try to find the solution.

**Comment by chusnaval** [comment]
I found that github Dependency Graph can't resolve in the past versions that are specified in a parent pom:

https://github.community/t/dependency-graph-not-resolving-versions-from-parent-pom/1432

I think that's the actual behaviour, i forked your repo and move all dependencies versions to properties. 
As you can see in: https://github.com/chusnaval/dss/network/dependencies in parent pom you can see all the versions numbers but in core pom all disappear. I think that put corresponding versions in core pom.xml may fix the problem.

If you want I test that possible solution and create a PR.

Chears

**Comment by ztkmkoo** [comment]
@chusnaval 
Hi, i'll be so happy if you create the pr.

**Comment by ztkmkoo** [comment]
![image](https://user-images.githubusercontent.com/26991409/89716554-e40e3d80-d9e8-11ea-83e1-acd37c8c0ad1.png)

Why the root pom.xml dependency version is hide??
