### ISSUE TITLE
Please implement dss network interface make dss server can accept tcp protocol

### ISSUE THREAD

**Issue by ztkmkoo** [ztkmkoo/dss#82]
Please implement DssChannel, DssChannelInitializer, DssChannelProperty, DssHandler and DssServer, make dss server can listen tcp protocol.

Please ref #81

**Comment by ztkmkoo** [comment]
@yeonnseok 
Can you try this?

**Comment by yeonnseok** [comment]
okay! i will try this one

**Comment by yeonnseok** [comment]
@ztkmkoo 
I am struggling to resolve it and I don't have any idea to test TCP request. 
Do I need to create some methods or just add StringEncoder/Decoder on ChannelInitializer for TCP request?

**Comment by ztkmkoo** [comment]
@yeonnseok 
Hi, 

Test tcp, you can
- use java IO / NIO socket
  - IO: https://www.codejava.net/java-se/networking/java-socket-client-examples-tcp-ip
  - NIO(see client part): https://examples.javacodegeeks.com/core-java/nio/java-nio-socket-example/
- use netty tcp client
  - https://netty.io/4.1/xref/io/netty/example/echo/package-summary.html

First, you dont have to implement service layer. (just can accept tcp connect and receive message is ok)
Then, (look at io.github.ztkmkoo.dss.core.network.rest package, this package implement rest layer)
- Create io.github.ztkmkoo.dss.core.network.tcp package in dss-common module
- implements `io.github.ztkmkoo.dss.core.network.DssChannel`
- implements `io.github.ztkmkoo.dss.core.network.DssChannelProperty`
- implements `io.github.ztkmkoo.dss.core.network.DssChannelInitializer` ( you do not have to implements DssActorAcceptable)
- implements `io.github.ztkmkoo.dss.core.network.DssHandler` ( you do not have to implements DssActorAcceptable)

You complete the steps then can receive tcp messages and make the pr!
