### ISSUE TITLE
Load test dss rest server performance

### ISSUE THREAD

**Issue by ztkmkoo** [ztkmkoo/dss#87]
Make a simple(echo) rest server, deploy to a cloud server and run it.
Use gatling(https://gatling.io/) or other tool to test server performance.

And push the echo server code, jar(jave archive) and test results under benchmark repository.

**Comment by ztkmkoo** [comment]
https://github.com/ztkmkoo/dss/blob/develop/benchmark/dss/GUIDE.md

**Comment by ParkSale** [comment]
@ParkSale  I want to try this

**Comment by ParkSale** [comment]
[result.zip](https://github.com/ztkmkoo/dss/files/5039482/result.zip)

I get that result.
but premature close error is appeared.
please advise me

**Comment by ParkSale** [comment]
```
package org.example

import scala.concurrent.duration._

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import io.gatling.jdbc.Predef._

class RecordedSimulation extends Simulation {

	val httpProtocol = http
		.baseUrl("http://127.0.0.1:8181")
		.acceptHeader("text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8")
		.doNotTrackHeader("1")
		.acceptEncodingHeader("gzip, deflate")
		.acceptLanguageHeader("ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7")
		.userAgentHeader("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36")

	val scn = scenario("RecordedSimulation")
		.exec(http("request_1")
			.get("/hello")
			.header(HttpHeaderNames.ContentType, HttpHeaderValues.ApplicationJson)
			.body(StringBody("""Test""")))



	setUp(
  		scn.inject(
		nothingFor(4 seconds),
		atOnceUsers(10),
		rampUsers(10) during (5 seconds),
		constantUsersPerSec(20) during (15 seconds),
		constantUsersPerSec(20) during (15 seconds) randomized,
		rampUsersPerSec(10) to 20 during (10 minutes),
		rampUsersPerSec(10) to 20 during (10 minutes) randomized,
		heavisideUsers(1000) during (20 seconds)
	).protocols(httpProtocol)
)
}
```

and I simulate with this code

**Comment by ztkmkoo** [comment]
Could you show me the server error log?

**Comment by ParkSale** [comment]
[ServerLog.txt](https://github.com/ztkmkoo/dss/files/5039838/ServerLog.txt)

Here is a LogFile.

**Comment by ztkmkoo** [comment]
@ParkSale 
Thank you for reporting the log file.

It looks some error occurred in at io.github.ztkmkoo.dss.core.network.rest.handler.DssRestHandler.handlingDssRestRequest(DssRestHandler.java:142)
``` java
Objects.requireNonNull(context);
```

It seems, the io request was pushed before the handler was ready..
I will fix it in other issue.

**Comment by ztkmkoo** [comment]
@ParkSale 
Could you deploy your test server to public server?

(and which port should i open?)

**Comment by ParkSale** [comment]
please open 8181 port. I will use that

**Comment by ztkmkoo** [comment]
@ParkSale 
I open the port, please tell me if not working

**Comment by ParkSale** [comment]
I have a question that adding server and client spec

what type of file that I add?

And In server, is it sure that using 'cat /proc/cpuinfo' for server spec?

**Comment by ztkmkoo** [comment]
> 
> 
> I have a question that adding server and client spec
> 
> what type of file that I add?
> 
> And In server, is it sure that using 'cat /proc/cpuinfo' for server spec?

Hi, i reply you on the pr. Please check it.
