### ISSUE TITLE
[BUG] NullPointerException in DssRestActorJsonService.java

### ISSUE THREAD

**Issue by Alencion** [ztkmkoo/dss#90]
**Describe the bug**
When json content is mapped to a jsonRequest class, NullPointerException occurs if the field in jsonRequest class is less than jsonContent.

**Screenshots**
``` java
    // final String sendJsonBody = "{\"name\":\"myname\",\"age\":20}";
    @Getter @Setter
    private static class TestJsonRequest implements Serializable {
        private String name;
    }
```
like this.

**Expected behavior**
Need to know why failed to mapping not NullPointerException.

**Comment by ztkmkoo** [comment]
@Alencion 
Hi, thank you for reporting bug.

I see if mapping json failed will return null object, and if you call the object member method will throw and null point exception.
Can you try to resolve this bug?

**Comment by Alencion** [comment]
ok. I'll try it
